### ISSUE TITLE
Loader error

### ISSUE THREAD

**Issue by kjetilge** [komushi/vue-cli-plugin-appsync#1]
When running the local server I get::

```
 error  in ./src/appsync/graphql/CreateBook.gql

Module parse failed: Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
```

I suspect this is because graphql-tag is not installed and configured correctly.

Usually it's possible to find web pack config files in a build folder but it's no where to be found.
How can I configure loaders for this project ?

**Comment by komushi** [comment]
Could you show me the steps to re-produce the error?

**Comment by komushi** [comment]
From vue-cli 3.x.x the webpack config is maintained internally.

[vuejs guide webpack](https://cli.vuejs.org/guide/webpack.html#chaining-advanced)

In this plugin .gql and .graphql will be handled by an additional rule.

```
    const rule = webpackConfig.module
      .rule('gql')
      .test(/\.(gql|graphql)$/)
      .include
      .add(api.resolve('src'))
      .add(api.resolve('tests'))
      .end()
      .use('cache-loader')
      .loader('cache-loader')
      .options({ cacheDirectory })
      .end()
```

By following the steps you should not see the errors.
Let me close the issue for now.

Thanks
